---
- hosts: all
  become: yes
  vars:
    #Linux distribution to download
    - distro_download_url: http://archlinuxarm.org/os/
    - distro_archive_name: ArchLinuxARM-rpi-2-latest
    - boot_disk: { id: 1, name: boot, fs: vfat }
    - root_disk: { id: 2, name: root, fs: ext4 }
    - disks: 
        - { id: "{{boot_disk.id}}", name: "{{boot_disk.name}}", fs: "{{boot_disk.fs}}" }
        - { id: "{{root_disk.id}}", name: "{{root_disk.name}}", fs: "{{root_disk.fs}}" }
    - device_id: sdb
  tasks:
    - apt: update_cache=yes
    - name: Install packages
      package: name={{item}} state=latest
      with_items:
        - dosfstools
        - bsdtar
        - parted
    - name: Remove previously created partitions
      command: dd if=/dev/zero of=/dev/{{device_id}} bs=512 count=1
    - name: Create partitions
      shell: parted -a optimal /dev/{{device_id}} -- mklabel msdos mkpart primary fat32 1MiB 100MiB mkpart primary ext4 100MiB -1s && parted /dev/{{device_id}} set 1 boot on
    - name: Format partitions
      command: "mkfs.{{item.fs}} /dev/{{device_id}}{{item.id}}"
      with_items: disks
    - name: Mount partitions
      mount: name=/tmp/{{item.name}} src=/dev/{{device_id}}{{item.id}} fstype={{item.fs}} state=mounted
      with_items: disks
    - name: Download distro
      get_url: url={{distro_download_url}}{{distro_archive_name}}.tar.gz dest=/vagrant/{{distro_archive_name}}.tar.gz
    - name: Unarchive distro to root disk
      shell: su -c "bsdtar -xpf /vagrant/{{distro_archive_name}}.tar.gz -C /tmp/{{root_disk.name}}" && sync
      become_user: root
    - name: Copy boot files to the first partition
      shell: mv /tmp/{{root_disk.name}}/boot/* /tmp/{{boot_disk.name}}
      become_user: root
    - name: Unmount disks
      mount: name=/tmp/{{item.name}} src=/dev/{{device_id}}{{item.id}} fstype={{item.fs}} state=unmounted
      with_items: disks
    - name: Generate image copy
      command: dd if=/dev/{{device_id}} of=/vagrant/{{distro_archive_name}}.img bs=1M
      when: make_image_file